//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booklists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booklists()
        {
            this.linkAspNetUsersBooklists = new HashSet<linkAspNetUsersBooklists>();
            this.linkBooklistsBooks = new HashSet<linkBooklistsBooks>();
        }
    
        public int booklistId { get; set; }
        public string booklistName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<linkAspNetUsersBooklists> linkAspNetUsersBooklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<linkBooklistsBooks> linkBooklistsBooks { get; set; }
    }
}
