//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCollection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnectionEntities : DbContext
    {
        public DefaultConnectionEntities()
            : base("name=DefaultConnectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booklists> Booklists { get; set; }
        public virtual DbSet<linkAspNetUsersBooklists> linkAspNetUsersBooklists { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<linkBooklistsBooks> linkBooklistsBooks { get; set; }
        public virtual DbSet<BooklistDetailView> BooklistDetailView { get; set; }
    }
}
